### ISSUE TITLE
Using ModuleAndWorkerAwareSpringBootApplication for workflow properties does not work properly

### ISSUE THREAD

**Issue by stephanpelikan** [vanillabp/spring-boot-support#21]
Using

```yaml
vanillabp:
   workflow-modules:
        xxxx:
            resources-location: classpath:xxxxx/bpmn
```

brings an error since this property-file is not loaded before the adapters initialize.
